#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue May 12 13:31:25 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
